require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ArgumentsController do

  # This should return the minimal set of attributes required to create a valid
  # Argument. As you add validations to Argument, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ArgumentsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all arguments as @arguments" do
      argument = Argument.create! valid_attributes
      get :index, {}, valid_session
      assigns(:arguments).should eq([argument])
    end
  end

  describe "GET show" do
    it "assigns the requested argument as @argument" do
      argument = Argument.create! valid_attributes
      get :show, {:id => argument.to_param}, valid_session
      assigns(:argument).should eq(argument)
    end
  end

  describe "GET new" do
    it "assigns a new argument as @argument" do
      get :new, {}, valid_session
      assigns(:argument).should be_a_new(Argument)
    end
  end

  describe "GET edit" do
    it "assigns the requested argument as @argument" do
      argument = Argument.create! valid_attributes
      get :edit, {:id => argument.to_param}, valid_session
      assigns(:argument).should eq(argument)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Argument" do
        expect {
          post :create, {:argument => valid_attributes}, valid_session
        }.to change(Argument, :count).by(1)
      end

      it "assigns a newly created argument as @argument" do
        post :create, {:argument => valid_attributes}, valid_session
        assigns(:argument).should be_a(Argument)
        assigns(:argument).should be_persisted
      end

      it "redirects to the created argument" do
        post :create, {:argument => valid_attributes}, valid_session
        response.should redirect_to(Argument.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved argument as @argument" do
        # Trigger the behavior that occurs when invalid params are submitted
        Argument.any_instance.stub(:save).and_return(false)
        post :create, {:argument => {}}, valid_session
        assigns(:argument).should be_a_new(Argument)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Argument.any_instance.stub(:save).and_return(false)
        post :create, {:argument => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested argument" do
        argument = Argument.create! valid_attributes
        # Assuming there are no other arguments in the database, this
        # specifies that the Argument created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Argument.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => argument.to_param, :argument => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested argument as @argument" do
        argument = Argument.create! valid_attributes
        put :update, {:id => argument.to_param, :argument => valid_attributes}, valid_session
        assigns(:argument).should eq(argument)
      end

      it "redirects to the argument" do
        argument = Argument.create! valid_attributes
        put :update, {:id => argument.to_param, :argument => valid_attributes}, valid_session
        response.should redirect_to(argument)
      end
    end

    describe "with invalid params" do
      it "assigns the argument as @argument" do
        argument = Argument.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Argument.any_instance.stub(:save).and_return(false)
        put :update, {:id => argument.to_param, :argument => {}}, valid_session
        assigns(:argument).should eq(argument)
      end

      it "re-renders the 'edit' template" do
        argument = Argument.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Argument.any_instance.stub(:save).and_return(false)
        put :update, {:id => argument.to_param, :argument => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested argument" do
      argument = Argument.create! valid_attributes
      expect {
        delete :destroy, {:id => argument.to_param}, valid_session
      }.to change(Argument, :count).by(-1)
    end

    it "redirects to the arguments list" do
      argument = Argument.create! valid_attributes
      delete :destroy, {:id => argument.to_param}, valid_session
      response.should redirect_to(arguments_url)
    end
  end

end
